version: '3'

services:
  godaddy-ddns:
    image: com.hmassad/godaddy-ddns
    environment:
      - GODADDY_API_KEY=${GODADDY_API_KEY}
      - GODADDY_API_SECRET=${GODADDY_API_SECRET}
      - GODADDY_DOMAIN=${GODADDY_DOMAIN}
      - GODADDY_HOST=${GODADDY_HOST}
      - SCHEDULER_INTERVAL=${SCHEDULER_INTERVAL}
